### ISSUE TITLE
Generic session out of date

### ISSUE THREAD

**Issue by donny-dont** [rvagg/node-level-session#11]
I'm attempting to use an on-prem install of https://david-dm.org/. I found myself running into an issue with the sessions timing out, https://github.com/alanshaw/david-www/issues/159. After investigating I found that there was a similar issue reported in generic-session, https://github.com/rvagg/node-generic-session/issues/2. I manually changed the value used by an `npm shrinkwrap` and the issue went away.

@rvagg would it be possible to update the version used here? I don't see a lot of activity for the session libs but it would be great to get the version bumped and a new package pushed.

**Comment by rvagg** [comment]
fixed, also did a bit of work on generic-session and updated dependencies there too, thanks

**Comment by donny-dont** [comment]
@rvagg thank you for taking the time :+1:

**Comment by alanshaw** [comment]
:thumbsup:
