### ISSUE TITLE
How to connect to multilevel and save sessions in a sublevel there? (`Error: client cannot create new sublevels`)

### ISSUE THREAD

**Issue by Industrial** [rvagg/node-level-session#4]
Hi.

I would like to store the session information in a central place and access and share it across a few processes. Say I have several HTTP microservices that would want to use the same session information; One proxy, One Login/Authc/Authz and one Admin (e.g. the actual site).

I have one Multilevel server running with a manifest written and a sublevel called "sessions". I called the sublevel with require("level-session")(db.sublevel("sessions")) on the leveldb server side but I'm not sure if that's needed.

The problem I'm having is that when I want to connect to the multilevel server with level-session I get: `Error: client cannot create new sublevels`.

**Comment by rvagg** [comment]
given the age of this and the lack of an answer (sorry), I'm closing it

**Comment by Industrial** [comment]
Agreed, I'm not working with leveldb at the moment either so :-)
